// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRTMkz88_UIpl0xMGse_CQPiXYiC8kik',
    appId: '1:60254233745:android:722876389d813b81c54b30',
    messagingSenderId: '60254233745',
    projectId: 'kippy-c3228',
    storageBucket: 'kippy-c3228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXL_bPngquASVtZmdW9CAnLPNGrGfUu8s',
    appId: '1:60254233745:ios:0cea847d80a6b1d2c54b30',
    messagingSenderId: '60254233745',
    projectId: 'kippy-c3228',
    storageBucket: 'kippy-c3228.firebasestorage.app',
    iosClientId: '60254233745-inhtftul906l39h8n0d6s1bv4qgll5fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.kippy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO_XLlaUow2sWbwiPkz0mcPptWtyvKUCI',
    appId: '1:60254233745:web:4d6feb33a97014d4c54b30',
    messagingSenderId: '60254233745',
    projectId: 'kippy-c3228',
    authDomain: 'kippy-c3228.firebaseapp.com',
    storageBucket: 'kippy-c3228.firebasestorage.app',
    measurementId: 'G-D8P8X0T3YL',
  );

}